import re
import os
import tempfile
import subprocess
from typing import TypedDict, List, Tuple

from db import MessageStatus, GAMES_PATH


class ParsedResponse(TypedDict):
    text: str
    diff: str
    status: MessageStatus


response_format_prompt = """\
Respond with an xml block with the following format:

<gg_message>
# The text to display to the user.
</gg_message>
<gg_find>
# A snipped of original code (with spacing!) to be replaced. The parser will 
# literally replace this text with the text in <gg_replace>.
</gg_find>
<gg_replace>
# New code to replace the text in <gg_find>.
</gg_replace>

Follow these guidelines absolutely:
- Only respond in the above format. Any text before or after the xml block, or xml tags other than those above, will be ignored.
- You can provide no find/replace paris, one, or multiple.
- Make sure each xml tag is on its own line with no spaces before/after the tag name.
- Make sure the xml block is properly terminated.
"""


def extract_message(response: str) -> str:
    """Extract the message text from the response."""
    message_match = re.search(
        r"<gg_message>\s*(.*?)\s*</gg_message>", response, re.DOTALL
    )
    return message_match.group(1) if message_match else ""


def extract_find_replace_pairs(response: str) -> List[Tuple[str, str]]:
    """Extract find/replace pairs from the response."""
    find_blocks = re.findall(r"<gg_find>\s*(.*?)\s*</gg_find>", response, re.DOTALL)
    replace_blocks = re.findall(
        r"<gg_replace>\s*(.*?)\s*</gg_replace>", response, re.DOTALL
    )

    # Ensure we have matching pairs
    if len(find_blocks) != len(replace_blocks):
        return []

    return list(zip(find_blocks, replace_blocks))


def generate_git_diff(original_code: str, modified_code: str) -> str:
    """
    Generate a diff using git diff command.

    Args:
        original_code: The original code
        modified_code: The modified code after applying changes

    Returns:
        A diff string generated by git diff
    """
    if original_code == modified_code:
        return ""

    # Create temporary files for the original and modified code
    with tempfile.NamedTemporaryFile(
        mode="w", delete=False, suffix=".html"
    ) as original_file:
        original_file_path = original_file.name
        original_file.write(original_code)

    with tempfile.NamedTemporaryFile(
        mode="w", delete=False, suffix=".html"
    ) as modified_file:
        modified_file_path = modified_file.name
        modified_file.write(modified_code)

    try:
        # Run git diff command
        result = subprocess.run(
            ["git", "diff", "--no-index", original_file_path, modified_file_path],
            capture_output=True,
            text=True,
            check=False,  # Don't raise an exception if git diff returns non-zero (which it does when there are differences)
        )

        # Git diff returns with exit code 1 if there are differences, which is expected
        diff_output = result.stdout

        # Clean up the diff output to remove the temporary file paths
        diff_output = re.sub(
            r"^--- .*?\.html$", "--- a/index.html", diff_output, flags=re.MULTILINE
        )
        diff_output = re.sub(
            r"^\+\+\+ .*?\.html$", "+++ b/index.html", diff_output, flags=re.MULTILINE
        )

        return diff_output
    finally:
        # Clean up temporary files
        os.unlink(original_file_path)
        os.unlink(modified_file_path)


def parse_response(
    response: str, game_path: str | None = None, code: str | None = None
) -> ParsedResponse:
    """
    Parse the XML response from the AI assistant.

    Extracts the message text and find/replace pairs, and generates a diff representation
    using git diff.

    Args:
        response: The XML response from the AI assistant
        game_path: The path to the game directory (optional)
        code: The original code (optional, will be read from game_path if not provided)

    Returns:
        A ParsedResponse object containing the message text, diff, and status
    """
    try:
        # Extract message text
        text = extract_message(response)

        # Extract find/replace pairs
        find_replace_pairs = extract_find_replace_pairs(response)

        # If there are no find/replace pairs, return early
        if not find_replace_pairs:
            return ParsedResponse(
                text=text,
                diff="",
                status=MessageStatus.COMPLETED if text else MessageStatus.ERROR,
            )

        # Get the original code
        if code is None and game_path is not None:
            try:
                with open(os.path.join(GAMES_PATH, game_path, "index.html"), "r") as f:
                    code = f.read()
            except FileNotFoundError:
                return ParsedResponse(text=text, diff="", status=MessageStatus.ERROR)

        if code is None:
            return ParsedResponse(text=text, diff="", status=MessageStatus.ERROR)

        # Apply the changes to get the modified code
        modified_code = apply_changes(code, find_replace_pairs)

        # Generate diff using git diff
        diff = generate_git_diff(code, modified_code)

        return ParsedResponse(text=text, diff=diff, status=MessageStatus.COMPLETED)
    except Exception as e:
        # If any error occurs during parsing, return an error response
        return ParsedResponse(
            text=f"Error parsing response: {str(e)}",
            diff="",
            status=MessageStatus.ERROR,
        )


def apply_changes(code: str, find_replace_pairs: List[Tuple[str, str]]) -> str:
    """
    Apply the find/replace changes to the game code.

    Args:
        code: The original game code
        find_replace_pairs: A list of (find, replace) tuples

    Returns:
        The modified game code
    """
    result = code
    for find, replace in find_replace_pairs:
        result = result.replace(find, replace)
    return result
